import React from 'react';

const WarehouseData =[
    {    
        key:1,
        Wtital: "Sugar Warehouse",
        Wrank: "3",
        Wrating: "4.3",
        Wreview: "100",
        Wpendingreview: "4",
        Wdiscription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
        Wregion: "United Kingdom",
        Wcommune: "sugar work Society",
        Waddress: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        Wfeatureservices: "gacacubc,yucsbubacb,ubasb",
        Wlink: "www.warehouse.com",
        Wpromotionaltax: "paid",
    },
    {
        key:2,
        Wtital: "Banana Warehouse",
        Wrank: "4",
        Wrating: "4",
        Wreview: "10",
        Wpendingreview: "2",
        Wdiscription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
        Wregion: "United State",
        Wcommune: "banana work Society",
        Waddress: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        Wfeatureservices: "uasucbubua,huascub,uyausu",
        Wlink: "www.warehouse.com",
        Wpromotionaltax: "Unpaid", 
    },   
    {
        key:3,
        Wtital: "Sugar Warehouse",
        Wrank: "3",
        Wrating: "4.3",
        Wreview: "100",
        Wpendingreview: "4",
        Wdiscription: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s",
        Wregion: "United Kingdom",
        Wcommune: "sugar work Society",
        Waddress: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
        Wfeatureservices: "gacacubc,yucsbubacb,ubasb",
        Wlink: "www.warehouse.com",
        Wpromotionaltax: "paid",
    },
]
export default WarehouseData;